# Generated by Django 4.2.30 on 2026-09-28 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='close_time',
            field=models.TimeField(default=datetime.time(20, 0), verbose_name='cierra a'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='open_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='abre a'),
        ),
    ]
