# Generated by Django 4.2.30 on 2026-09-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_rename_branch_to_establishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberprofile',
            name='work_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Horario por día (0=domingo … 6=sábado).', verbose_name='horarios de trabajo'),
        ),
    ]
