# Generated by Django 4.2.30 on 2026-09-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_barber_work_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='barbers/', verbose_name='foto de perfil'),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='work_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Horario por día (0=domingo … 6=sábado). Soporta varios rangos.', verbose_name='horarios de trabajo'),
        ),
    ]
